import type { Category, Ingredient, Recipe, Unit } from "./types";

export const categories: Category[] = [
  "蔬菜类",
  "肉类",
  "蛋奶类",
  "豆制品",
  "主食类",
  "水果类",
  "调料类",
  "酱料类",
  "速食品/冷冻食品",
  "其他",
];

export const units: Unit[] = ["克", "个", "颗", "袋", "盒", "瓶", "勺", "小勺", "碗", "份", "把", "根", "片", "瓣", "听", "块"];

export const commonIngredients: Record<Category, string[]> = {
  蔬菜类: ["青菜", "白菜", "土豆", "番茄", "黄瓜", "胡萝卜", "洋葱", "蘑菇", "茄子", "西兰花", "青椒"],
  肉类: ["猪肉", "牛肉", "鸡肉", "鸡翅", "羊肉", "鱼", "虾", "培根", "火腿"],
  蛋奶类: ["鸡蛋", "牛奶", "奶酪", "酸奶"],
  豆制品: ["豆腐", "豆皮", "豆干", "腐竹"],
  主食类: ["米饭", "面条", "馒头", "饺子皮", "面粉", "土豆粉", "粉丝"],
  水果类: ["苹果", "香蕉", "橙子", "草莓"],
  调料类: ["盐", "糖", "生抽", "老抽", "蚝油", "醋", "料酒", "辣椒", "蒜", "姜", "葱", "花椒", "孜然", "咖喱"],
  酱料类: ["番茄酱", "豆瓣酱", "黄豆酱", "沙拉酱", "辣椒酱"],
  "速食品/冷冻食品": ["速冻饺子", "冷冻鸡块", "丸子", "火锅底料"],
  其他: ["紫菜", "香菇", "木耳", "芝麻", "可乐"],
};

export const nutritionSamples = [
  { name: "鸡蛋", calories: 144, protein: 13.3, fat: 8.8, carbs: 2.8, fiber: 0, sodium: 131, unit: "每100克" },
  { name: "番茄", calories: 15, protein: 0.9, fat: 0.2, carbs: 3.3, fiber: 1.1, sodium: 5, unit: "每100克" },
  { name: "猪肉", calories: 143, protein: 20.3, fat: 6.2, carbs: 1.5, fiber: 0, sodium: 57, unit: "每100克" },
  { name: "土豆", calories: 81, protein: 2.6, fat: 0.2, carbs: 17.8, fiber: 1.1, sodium: 3, unit: "每100克" },
  { name: "豆腐", calories: 84, protein: 6.6, fat: 5.3, carbs: 3.4, fiber: 0.4, sodium: 7, unit: "每100克" },
  { name: "米饭", calories: 116, protein: 2.6, fat: 0.3, carbs: 25.9, fiber: 0.3, sodium: 2, unit: "每100克" },
];

export const starterInventory: Ingredient[] = [
  {
    id: "ing-1",
    name: "猪里脊肉",
    category: "肉类",
    quantity: 1,
    unit: "份",
    expiringSoon: false,
    purchaseDate: "",
    expiryDate: "",
    note: "可识别为猪肉",
  },
  {
    id: "ing-2",
    name: "鸡蛋",
    category: "蛋奶类",
    quantity: 1,
    unit: "个",
    expiringSoon: false,
    purchaseDate: "",
    expiryDate: "",
    note: "",
  },
];

const i = (
  name: string,
  amount: number,
  unit: Unit,
  category: Category,
  required: boolean,
  role: "main" | "assistant" | "staple" | "seasoning",
) => ({ name, amount, unit, category, required, role });

export const recipes: Recipe[] = [
  {
    id: "steamed-egg",
    name: "鸡蛋羹",
    emoji: "🥚",
    description: "嫩嫩滑滑的蒸蛋，一人一个蛋也能做。",
    category: "蛋菜",
    taste: ["清淡", "家常"],
    difficulty: "简单",
    minutes: 15,
    servings: 1,
    mealTypes: ["早餐", "午餐", "晚餐"],
    tags: ["快手", "清淡", "减油", "高蛋白"],
    ingredients: [i("鸡蛋", 1, "个", "蛋奶类", true, "main")],
    seasonings: [i("盐", 0.3, "小勺", "调料类", false, "seasoning"), i("生抽", 0.5, "勺", "调料类", false, "seasoning")],
    steps: ["鸡蛋打散，加入约1.5倍温水和一点点盐。", "过滤到碗里，盖盘子或保鲜膜。", "水开后中小火蒸10分钟，出锅淋少许生抽。"],
    tips: ["温水和过滤能让蛋羹更细腻。"],
    alternatives: ["可以加虾仁、肉末或葱花。"],
    nutritionPerServing: { calories: 110, protein: 7, fat: 7, carbs: 2, fiber: 0, sodium: 260 },
  },
  {
    id: "fried-egg",
    name: "煎鸡蛋",
    emoji: "🍳",
    description: "最省心的快手蛋白质，早餐或夜宵都合适。",
    category: "蛋菜",
    taste: ["家常"],
    difficulty: "简单",
    minutes: 6,
    servings: 1,
    mealTypes: ["早餐", "午餐", "晚餐", "夜宵"],
    tags: ["快手", "高蛋白"],
    ingredients: [i("鸡蛋", 1, "个", "蛋奶类", true, "main")],
    seasonings: [i("盐", 0.2, "小勺", "调料类", false, "seasoning")],
    steps: ["锅里少油，小火打入鸡蛋。", "蛋白凝固后撒一点盐。", "喜欢全熟就翻面再煎30秒。"],
    tips: ["小火更不容易糊。"],
    alternatives: ["可以撒黑胡椒或淋少许生抽。"],
    nutritionPerServing: { calories: 120, protein: 7, fat: 9, carbs: 1, fiber: 0, sodium: 180 },
  },
  {
    id: "minced-pork-steamed-egg",
    name: "肉末蒸蛋",
    emoji: "🥣",
    description: "鸡蛋和猪肉刚好能搭起来，软嫩又有肉香。",
    category: "蛋白质主菜",
    taste: ["清淡", "家常"],
    difficulty: "简单",
    minutes: 20,
    servings: 2,
    mealTypes: ["午餐", "晚餐"],
    tags: ["高蛋白", "家常", "快手", "肉菜"],
    ingredients: [i("鸡蛋", 2, "个", "蛋奶类", true, "main"), i("猪肉", 100, "克", "肉类", true, "main")],
    seasonings: [i("生抽", 1, "勺", "调料类", false, "seasoning"), i("葱", 0.5, "把", "调料类", false, "seasoning"), i("盐", 0.3, "小勺", "调料类", false, "seasoning")],
    steps: ["猪肉剁成肉末，加半勺生抽抓匀。", "鸡蛋加温水打散，倒入碗中。", "肉末铺在蛋液上，水开蒸12-15分钟。", "出锅淋少许生抽，撒葱花。"],
    tips: ["肉末不要太厚，熟得更均匀。"],
    alternatives: ["猪肉可换虾仁或鸡肉末。"],
    nutritionPerServing: { calories: 210, protein: 18, fat: 13, carbs: 3, fiber: 0, sodium: 520 },
  },
  {
    id: "pork-egg-stir",
    name: "猪肉炒蛋",
    emoji: "🥢",
    description: "有肉有蛋的家常快手菜，库存少时也能撑起一顿。",
    category: "蛋白质主菜",
    taste: ["家常", "下饭"],
    difficulty: "简单",
    minutes: 15,
    servings: 2,
    mealTypes: ["午餐", "晚餐"],
    tags: ["高蛋白", "快手", "肉菜", "下饭"],
    ingredients: [i("猪肉", 150, "克", "肉类", true, "main"), i("鸡蛋", 2, "个", "蛋奶类", true, "main")],
    seasonings: [i("生抽", 1, "勺", "调料类", false, "seasoning"), i("盐", 0.3, "小勺", "调料类", false, "seasoning"), i("葱", 0.5, "把", "调料类", false, "seasoning")],
    steps: ["猪肉切薄片或肉丝，加一点生抽抓匀。", "鸡蛋打散先炒到刚凝固盛出。", "锅里炒猪肉至变色，倒回鸡蛋，加盐调味。"],
    tips: ["鸡蛋先盛出，口感不会老。"],
    alternatives: ["可以加青椒、洋葱或番茄。"],
    nutritionPerServing: { calories: 280, protein: 24, fat: 18, carbs: 4, fiber: 0, sodium: 550 },
  },
  {
    id: "qingjiao-rousi",
    name: "青椒肉丝",
    emoji: "🫑",
    description: "经典下饭肉菜，有猪肉时缺个青椒就能做。",
    category: "肉菜",
    taste: ["家常", "下饭"],
    difficulty: "简单",
    minutes: 20,
    servings: 2,
    mealTypes: ["午餐", "晚餐"],
    tags: ["下饭", "家常", "肉菜", "快手"],
    ingredients: [i("猪肉", 200, "克", "肉类", true, "main"), i("青椒", 2, "个", "蔬菜类", true, "main")],
    seasonings: [i("盐", 0.5, "小勺", "调料类", false, "seasoning"), i("生抽", 1, "勺", "调料类", false, "seasoning"), i("淀粉", 1, "勺", "调料类", false, "seasoning")],
    steps: ["猪肉切丝，加生抽、淀粉抓匀腌制10分钟。", "青椒切丝备用。", "热锅下油，先炒肉丝至变色。", "加入青椒翻炒，加盐调味即可。"],
    tips: ["肉丝先抓淀粉会更嫩。"],
    alternatives: ["青椒可换洋葱、青菜或胡萝卜。"],
    nutritionPerServing: { calories: 260, protein: 22, fat: 14, carbs: 9, fiber: 2, sodium: 620 },
  },
  {
    id: "onion-pork",
    name: "洋葱炒肉",
    emoji: "🧅",
    description: "洋葱甜甜的，和猪肉很搭。",
    category: "肉菜",
    taste: ["家常", "下饭"],
    difficulty: "简单",
    minutes: 18,
    servings: 2,
    mealTypes: ["午餐", "晚餐"],
    tags: ["下饭", "家常", "肉菜", "快手"],
    ingredients: [i("猪肉", 180, "克", "肉类", true, "main"), i("洋葱", 1, "个", "蔬菜类", true, "main")],
    seasonings: [i("生抽", 1, "勺", "调料类", false, "seasoning"), i("盐", 0.3, "小勺", "调料类", false, "seasoning")],
    steps: ["猪肉切片，洋葱切丝。", "先炒猪肉至变色。", "加入洋葱炒软，生抽和盐调味。"],
    tips: ["洋葱炒到微透明会更甜。"],
    alternatives: ["洋葱可换青椒。"],
    nutritionPerServing: { calories: 250, protein: 20, fat: 14, carbs: 11, fiber: 2, sodium: 520 },
  },
  {
    id: "tomato-egg",
    name: "番茄炒蛋",
    emoji: "🍅",
    description: "酸甜开胃的家常菜，缺番茄时不会高分推荐。",
    category: "蛋菜",
    taste: ["酸甜", "家常"],
    difficulty: "简单",
    minutes: 15,
    servings: 2,
    mealTypes: ["午餐", "晚餐"],
    tags: ["快手", "下饭", "减油"],
    ingredients: [i("番茄", 2, "个", "蔬菜类", true, "main"), i("鸡蛋", 3, "个", "蛋奶类", true, "main")],
    seasonings: [i("葱", 0.5, "把", "调料类", false, "seasoning"), i("盐", 0.5, "小勺", "调料类", false, "seasoning"), i("糖", 0.5, "小勺", "调料类", false, "seasoning")],
    steps: ["鸡蛋打散，加一点点盐，锅热后先炒到刚凝固再盛出。", "番茄切小块，下锅慢慢炒出汁。", "倒回鸡蛋，加糖和盐调味，翻匀后撒葱花出锅。"],
    tips: ["番茄先切小块，更容易炒出汁。", "鸡蛋不要炒太老，后面还会回锅。"],
    alternatives: ["没有葱可以不放；想更浓郁可以加一点番茄酱。"],
    nutritionPerServing: { calories: 230, protein: 15, fat: 14, carbs: 12, fiber: 2, sodium: 560 },
  },
  {
    id: "egg-fried-rice",
    name: "蛋炒饭",
    emoji: "🍚",
    description: "剩米饭的温柔归宿，缺米饭时不会高分推荐。",
    category: "主食",
    taste: ["家常"],
    difficulty: "简单",
    minutes: 12,
    servings: 1,
    mealTypes: ["早餐", "午餐", "夜宵"],
    tags: ["快手", "主食"],
    ingredients: [i("米饭", 1, "碗", "主食类", true, "staple"), i("鸡蛋", 1, "个", "蛋奶类", true, "main"), i("火腿", 50, "克", "肉类", false, "assistant")],
    seasonings: [i("盐", 0.3, "小勺", "调料类", false, "seasoning"), i("生抽", 0.5, "勺", "调料类", false, "seasoning")],
    steps: ["鸡蛋炒散盛出。", "米饭下锅压散，加入火腿丁翻炒。", "倒回鸡蛋，加盐和生抽，最后撒葱花。"],
    tips: ["隔夜米饭更容易炒散。"],
    alternatives: ["火腿可以换胡萝卜丁、玉米粒或虾仁。"],
    nutritionPerServing: { calories: 520, protein: 18, fat: 16, carbs: 76, fiber: 2, sodium: 690 },
  },
  {
    id: "egg-noodles",
    name: "鸡蛋面",
    emoji: "🍜",
    description: "热乎乎的一碗，缺面条时不会高分推荐。",
    category: "汤面",
    taste: ["清淡", "家常"],
    difficulty: "简单",
    minutes: 15,
    servings: 1,
    mealTypes: ["早餐", "晚餐", "夜宵"],
    tags: ["快手", "汤类", "主食"],
    ingredients: [i("面条", 1, "份", "主食类", true, "staple"), i("鸡蛋", 1, "个", "蛋奶类", true, "main"), i("青菜", 0.5, "把", "蔬菜类", false, "assistant")],
    seasonings: [i("盐", 0.3, "小勺", "调料类", false, "seasoning"), i("生抽", 1, "勺", "调料类", false, "seasoning")],
    steps: ["水开下面条，煮到八成熟。", "打入鸡蛋或提前煎一个荷包蛋。", "放青菜，加盐和生抽调味，面熟后盛出。"],
    tips: ["青菜最后放，颜色更好看。"],
    alternatives: ["面条可以换粉丝、土豆粉或馒头片。"],
    nutritionPerServing: { calories: 430, protein: 17, fat: 10, carbs: 68, fiber: 3, sodium: 780 },
  },
  {
    id: "sour-potato",
    name: "酸辣土豆丝",
    emoji: "🥔",
    description: "脆爽开胃，配粥配饭都合适。",
    category: "素菜",
    taste: ["香辣", "家常"],
    difficulty: "简单",
    minutes: 15,
    servings: 2,
    mealTypes: ["午餐", "晚餐"],
    tags: ["快手", "辣一点", "下饭", "素菜"],
    ingredients: [i("土豆", 2, "个", "蔬菜类", true, "main")],
    seasonings: [i("醋", 2, "勺", "调料类", false, "seasoning"), i("盐", 0.5, "小勺", "调料类", false, "seasoning"), i("辣椒", 1, "个", "调料类", false, "seasoning")],
    steps: ["土豆切丝后用清水洗掉淀粉，沥干。", "热锅爆香辣椒，放土豆丝大火快炒。", "加醋和盐，土豆丝断生后马上出锅。"],
    tips: ["洗掉淀粉后会更脆。"],
    alternatives: ["不吃辣可以只放醋，做成清爽酸味。"],
    nutritionPerServing: { calories: 190, protein: 4, fat: 6, carbs: 32, fiber: 3, sodium: 520 },
  },
  {
    id: "cola-wings",
    name: "可乐鸡翅",
    emoji: "🍗",
    description: "甜咸口的小惊喜，缺鸡翅和可乐时不会高分推荐。",
    category: "肉菜",
    taste: ["酸甜", "家常"],
    difficulty: "简单",
    minutes: 30,
    servings: 2,
    mealTypes: ["午餐", "晚餐", "夜宵"],
    tags: ["下饭", "肉菜"],
    ingredients: [i("鸡翅", 500, "克", "肉类", true, "main"), i("可乐", 1, "瓶", "其他", true, "assistant")],
    seasonings: [i("姜", 3, "片", "调料类", false, "seasoning"), i("生抽", 2, "勺", "调料类", false, "seasoning")],
    steps: ["鸡翅两面划口，焯水后擦干。", "小火煎到两面微黄，加入姜片、生抽和可乐。", "中小火焖煮，最后大火收汁到挂在鸡翅上。"],
    tips: ["收汁时要看着锅，糖分高容易糊。"],
    alternatives: ["可乐可换无糖可乐，但味道会淡一些。"],
    nutritionPerServing: { calories: 480, protein: 28, fat: 25, carbs: 35, fiber: 0, sodium: 880 },
  },
];
